# Generated by Django 4.1.4 on 2023-02-26 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.IntegerField(blank=True, null=True, verbose_name='Numero de Ruc')),
                ('businessName', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razon Social')),
                ('tradename', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Comercial')),
                ('establishmentAddress', models.CharField(blank=True, max_length=150, null=True, verbose_name='direccion establecimiento')),
                ('senderAddress', models.CharField(blank=True, max_length=150, null=True, verbose_name='direccion emisor')),
                ('IssuerCode', models.IntegerField(blank=True, null=True, verbose_name='Codigo Emisor')),
                ('EmissionPoint', models.IntegerField(blank=True, null=True, verbose_name='Punto Emisión')),
                ('SpecialTaxpayer', models.IntegerField(blank=True, null=True, verbose_name='Contribuyente Especial')),
                ('Accounting', models.IntegerField(choices=[[1, 'No'], [2, 'Si']], default=1, verbose_name='Contabilidad')),
                ('Logo', models.FileField(blank=True, null=True, upload_to='logo', verbose_name='Logotipo de la Empresa')),
                ('ElectronicSignature', models.FileField(blank=True, null=True, upload_to='', verbose_name='Firma electronica')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
    ]
