# Generated by Django 4.1.4 on 2023-02-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='xml_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/xml/', verbose_name='Archivo XML'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='voucher_type',
            field=models.IntegerField(choices=[(1, 'Factura'), (3, 'Liquidacion de Compra de Bienes y Prestación de Servicios'), (4, 'Nota de Crédito'), (5, 'Nota de Débito'), (6, 'Guía de Remisión'), (7, 'Comprobante de Retención')], default=1, verbose_name='Tipo de Comprobante'),
        ),
    ]
