# Generated by Django 4.1.4 on 2023-02-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_code', models.IntegerField(unique=True, verbose_name='Codigo Principal')),
                ('auxiliary_code', models.IntegerField(unique=True, verbose_name='Codigo Auxiliar')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Producto')),
                ('stock', models.IntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Unitario')),
                ('vat_rate', models.IntegerField(choices=[[1, '0%'], [2, '12%'], [3, '14%'], [4, 'No Objeto de Impuesto'], [5, 'Exento de IVA']], default=1, verbose_name='Tipo de IVA')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'product',
            },
        ),
    ]
