# Generated by Django 4.1.4 on 2023-02-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identify', models.IntegerField(unique=True, verbose_name='Identificación')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cellPhone', models.CharField(max_length=10, verbose_name='Telefono/Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('addres', models.CharField(max_length=250, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
            },
        ),
    ]
